spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/agricultural?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.puyan.shengren.agricultural
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-boot.xml


RequestIp : http://localhost:8080
